/* Scintilla source code edit control */
/** @file SciLexer.h
 ** Interface to the added lexer functions in the SciLexer version of the edit control.
 **/
/* Copyright 1998-2002 by Neil Hodgson <neilh@scintilla.org>
 * The License.txt file describes the conditions under which this software may be distributed. */

/* Most of this file is automatically generated from the Scintilla.iface interface definition
 * file which contains any comments about the definitions. HFacer.py does the generation. */

#ifndef SCILEXER_H
#define SCILEXER_H

/* SciLexer features - not in standard Scintilla */

/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */
#define SCLEX_CONTAINER 0
#define SCLEX_NULL 1
#define SCLEX_AU3 60
#define SCLEX_JASS 99
#define SCLEX_AUTOMATIC 1000

#define SCE_JASS_DEFAULT		 0 // SCE_AU3_DEFAULT
#define SCE_JASS_COMMENTLINE	 1 // SCE_AU3_COMMENT
#define SCE_JASS_COMMENTBLOCK	 2 // SCE_AU3_COMMENTBLOCK
#define SCE_JASS_NUMBER			 3 // SCE_AU3_NUMBER
#define SCE_JASS_KEYWORD		 4 // SCE_AU3_FUNCTION
#define SCE_JASS_BLOCK			 5 // SCE_AU3_KEYWORD
#define SCE_JASS_VALUE			 6 // SCE_AU3_MACRO
#define SCE_JASS_STRING			 7 // SCE_AU3_STRING
#define SCE_JASS_OPERATOR		 8 // SCE_AU3_OPERATOR
#define SCE_JASS_VARIABLE		 9 // SCE_AU3_VARIABLE
#define SCE_JASS_SENT			10 // SCE_AU3_SENT
#define SCE_JASS_TYPE			11 // SCE_AU3_PREPROCESSOR
#define SCE_JASS_NATIVE			12 // SCE_AU3_SPECIAL
#define SCE_JASS_UDF			13 // SCE_AU3_EXPAND
#define SCE_JASS_COMOBJ			14 // SCE_AU3_COMOBJ
#define SCE_JASS_BJ				15 // SCE_AU3_UDF
#define SCE_JASS_PCOMM			16 // 
#define SCE_JASS_CONST			17 // 
#define SCE_JASS_RAWCODE		18 // 
#define SCE_JASS_SEMIKEYWORD	19 // 
//#define SCE_JASS_TYPE			20



#define SCE_AU3_DEFAULT			 0 //
#define SCE_AU3_COMMENT			 1 //
#define SCE_AU3_COMMENTBLOCK	 2 //
#define SCE_AU3_NUMBER			 3 //
#define SCE_AU3_FUNCTION		 4 // Keywords
#define SCE_AU3_KEYWORD			 5 // blocks
#define SCE_AU3_MACRO			 6 // value
#define SCE_AU3_STRING			 7 //
#define SCE_AU3_OPERATOR		 8 //
#define SCE_AU3_VARIABLE		 9 //
#define SCE_AU3_SENT			10 //
#define SCE_AU3_PREPROCESSOR	11 // types
#define SCE_AU3_SPECIAL			12 // natives
#define SCE_AU3_EXPAND			13 // 
#define SCE_AU3_COMOBJ			14 // comobj
#define SCE_AU3_UDF				15 // bj

#endif
